import React,{useState,useEffect}from 'react';import axios from 'axios';import Layout from '../../components/common/Layout';import toast from 'react-hot-toast';import{Award,Download,Edit,Plus,Send}from 'lucide-react';
export default function CertificateManagement(){
  const[tab,setTab]=useState('setting');const[certs,setCerts]=useState([]);const[apps,setApps]=useState([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
  const[setting,setSetting]=useState({title:'Certificate of Registration',authority:'QC Certification Pvt Ltd',validityYears:3,footerText:'This certificate is subject to certification body regulations.',accreditation:'NABCB'});
  const[manualForm,setManualForm]=useState({orgName:'',standard:'',scope:'',issueDate:'',expiryDate:'',certNumber:''});
  const[modifyForm,setModifyForm]=useState({appId:'',issueDate:'',expiryDate:'',certNumber:''});
  const load=()=>{setLoading(true);Promise.all([axios.get('/api/certificates'),axios.get('/api/applications')]).then(([c,a])=>{setCerts(c.data||[]);setApps(a.data||[]);}).finally(()=>setLoading(false));};useEffect(load,[]);
  const saveSetting=async()=>{setSaving(true);try{await axios.put('/api/certificates/settings',setting);toast.success('Settings saved');}catch{toast.error('Failed');}finally{setSaving(false);}};
  const issueManual=async()=>{if(!manualForm.orgName||!manualForm.standard)return toast.error('Organization and standard required');setSaving(true);try{await axios.post('/api/certificates/manual',manualForm);toast.success('Certificate issued');setManualForm({orgName:'',standard:'',scope:'',issueDate:'',expiryDate:'',certNumber:''});load();}catch{toast.error('Failed');}finally{setSaving(false);}};
  const modifyCert=async()=>{if(!modifyForm.appId)return toast.error('Select application');setSaving(true);try{await axios.put(`/api/certificates/${modifyForm.appId}`,modifyForm);toast.success('Updated');load();}catch{toast.error('Failed');}finally{setSaving(false);}};
  const TABS=[{id:'setting',label:'Certificate Setting'},{id:'modify',label:'Modify Certificate'},{id:'manual',label:'Manual Certificate'},{id:'download',label:'Download Certificate'}];
  return(<Layout title="Certificate Management">
    <div className="page-hdr"><div><h1 className="page-title">Certificate Management</h1><p className="page-subtitle">Configure and manage certifications</p></div></div>
    <div className="card"><div className="card-body">
      <div className="tabs-bar">{TABS.map(t=><button key={t.id} className={`tab-item ${tab===t.id?'active':''}`} onClick={()=>setTab(t.id)}>{t.label}</button>)}</div>
      {tab==='setting'&&(<div><div className="section-label">Certificate Template</div><div className="form-group"><label className="form-label">Certificate Title</label><input className="form-control" value={setting.title} onChange={e=>setSetting(p=>({...p,title:e.target.value}))}/></div><div className="form-group"><label className="form-label">Issuing Authority</label><input className="form-control" value={setting.authority} onChange={e=>setSetting(p=>({...p,authority:e.target.value}))}/></div><div className="form-row"><div className="form-group"><label className="form-label">Validity (Years)</label><input type="number" className="form-control" value={setting.validityYears} onChange={e=>setSetting(p=>({...p,validityYears:e.target.value}))}/></div><div className="form-group"><label className="form-label">Accreditation Body</label><select className="form-control" value={setting.accreditation} onChange={e=>setSetting(p=>({...p,accreditation:e.target.value}))}>{['NABCB','UKAS','DAkkS','NAB','ANAB'].map(b=><option key={b}>{b}</option>)}</select></div></div><div className="form-group"><label className="form-label">Footer Text</label><textarea className="form-control" rows={2} value={setting.footerText} onChange={e=>setSetting(p=>({...p,footerText:e.target.value}))}/></div><button className="btn btn-primary" onClick={saveSetting} disabled={saving}>{saving?'Saving…':'Save Settings'}</button></div>)}
      {tab==='modify'&&(<div><div className="section-label">Modify Existing Certificate</div><div className="form-group"><label className="form-label">Select Application *</label><select className="form-control" value={modifyForm.appId} onChange={e=>setModifyForm(p=>({...p,appId:e.target.value}))}><option value="">— Select —</option>{apps.filter(a=>['certified','approved'].includes(a.status)).map(a=><option key={a._id} value={a._id}>{a.applicationId} — {a.organizationName}</option>)}</select></div><div className="form-group"><label className="form-label">Certificate Number</label><input className="form-control" value={modifyForm.certNumber} onChange={e=>setModifyForm(p=>({...p,certNumber:e.target.value}))} placeholder="QC-2024-001"/></div><div className="form-row"><div className="form-group"><label className="form-label">Issue Date</label><input type="date" className="form-control" value={modifyForm.issueDate} onChange={e=>setModifyForm(p=>({...p,issueDate:e.target.value}))}/></div><div className="form-group"><label className="form-label">Expiry Date</label><input type="date" className="form-control" value={modifyForm.expiryDate} onChange={e=>setModifyForm(p=>({...p,expiryDate:e.target.value}))}/></div></div><button className="btn btn-primary" onClick={modifyCert} disabled={saving}><Edit size={14}/>{saving?'Updating…':'Update Certificate'}</button></div>)}
      {tab==='manual'&&(<div><div className="section-label">Issue Manual Certificate</div><div className="form-row"><div className="form-group"><label className="form-label">Organization Name *</label><input className="form-control" value={manualForm.orgName} onChange={e=>setManualForm(p=>({...p,orgName:e.target.value}))}/></div><div className="form-group"><label className="form-label">ISO Standard *</label><select className="form-control" value={manualForm.standard} onChange={e=>setManualForm(p=>({...p,standard:e.target.value}))}><option value="">— Select —</option>{['ISO 9001:2015','ISO 14001:2015','ISO 45001:2018','ISO 27001:2022','ISO 22000:2018'].map(s=><option key={s}>{s}</option>)}</select></div></div><div className="form-group"><label className="form-label">Scope</label><textarea className="form-control" rows={2} value={manualForm.scope} onChange={e=>setManualForm(p=>({...p,scope:e.target.value}))}/></div><div className="form-row"><div className="form-group"><label className="form-label">Certificate Number</label><input className="form-control" value={manualForm.certNumber} onChange={e=>setManualForm(p=>({...p,certNumber:e.target.value}))} placeholder="QC-MANUAL-001"/></div><div className="form-group"/></div><div className="form-row"><div className="form-group"><label className="form-label">Issue Date</label><input type="date" className="form-control" value={manualForm.issueDate} onChange={e=>setManualForm(p=>({...p,issueDate:e.target.value}))}/></div><div className="form-group"><label className="form-label">Expiry Date</label><input type="date" className="form-control" value={manualForm.expiryDate} onChange={e=>setManualForm(p=>({...p,expiryDate:e.target.value}))}/></div></div><button className="btn btn-primary" onClick={issueManual} disabled={saving}><Award size={14}/>{saving?'Issuing…':'Issue Certificate'}</button></div>)}
      {tab==='download'&&(<div><div className="section-label">Issued Certificates</div>{loading?<div className="loading-box"><div className="spinner"/></div>:(<div className="tbl-wrap"><table className="tbl"><thead><tr><th>Cert #</th><th>Organization</th><th>Standard</th><th>Issued</th><th>Expiry</th><th>Status</th><th>Action</th></tr></thead><tbody>{certs.map(c=>(<tr key={c._id}><td style={{fontFamily:'JetBrains Mono,monospace',fontSize:12}}>{c.certNumber||'—'}</td><td style={{fontWeight:600}}>{c.organizationName}</td><td style={{fontSize:12}}>{c.standard}</td><td style={{fontSize:12}}>{c.issueDate?new Date(c.issueDate).toLocaleDateString():'—'}</td><td style={{fontSize:12}}>{c.expiryDate?new Date(c.expiryDate).toLocaleDateString():'—'}</td><td><span className="badge bdg-certified">{c.status||'Active'}</span></td><td><div className="tbl-actions">{c.filePath&&<a href={c.filePath} download className="btn btn-secondary btn-sm"><Download size={13}/>Download</a>}<button className="btn btn-ghost btn-sm"><Send size={13}/>Send</button></div></td></tr>))}{certs.length===0&&<tr><td colSpan={7} style={{textAlign:'center',padding:32,color:'var(--gray-400)'}}>No certificates yet</td></tr>}</tbody></table></div>)}</div>)}
    </div></div>
  </Layout>);}
