import React,{useState,useEffect}from 'react';import axios from 'axios';import Layout from '../../components/common/Layout';import toast from 'react-hot-toast';import{Plus,Edit,Trash2,BookOpen}from 'lucide-react';
export default function AdminStandards(){
  const[standards,setStandards]=useState([]);const[loading,setLoading]=useState(true);const[modal,setModal]=useState(null);const[saving,setSaving]=useState(false);const[form,setForm]=useState({name:'',category:'',active:true});
  const load=()=>{setLoading(true);axios.get('/api/standards').then(r=>setStandards(r.data||[])).finally(()=>setLoading(false));};useEffect(load,[]);
  const save=async()=>{if(!form.name||!form.category)return toast.error('Name and category required');setSaving(true);try{if(modal==='add')await axios.post('/api/standards',form);else await axios.put(`/api/standards/${modal._id}`,form);toast.success(modal==='add'?'Added':'Updated');setModal(null);load();}catch(e){toast.error(e.response?.data?.message||'Error');}finally{setSaving(false);}};
  const del=async id=>{if(!window.confirm('Delete?'))return;try{await axios.delete(`/api/standards/${id}`);toast.success('Deleted');load();}catch{toast.error('Failed');}};
  return(<Layout title="Add Standard">
    <div className="page-hdr"><div><h1 className="page-title">ISO Standards</h1><p className="page-subtitle">{standards.length} configured</p></div><button className="btn btn-primary" onClick={()=>{setForm({name:'',category:'',active:true});setModal('add');}}><Plus size={14}/>Add Standard</button></div>
    <div className="card">{loading?<div className="loading-box"><div className="spinner"/></div>:(<div className="tbl-wrap"><table className="tbl"><thead><tr><th>#</th><th>Name</th><th>Category</th><th>Status</th><th>Actions</th></tr></thead><tbody>{standards.map((s,i)=>(<tr key={s._id}><td style={{color:'var(--gray-400)',fontSize:12}}>{i+1}</td><td><div style={{display:'flex',alignItems:'center',gap:8}}><BookOpen size={13} style={{color:'var(--primary)'}}/><strong>{s.name}</strong></div></td><td><span className="badge bdg-info" style={{background:'var(--primary-50)',color:'var(--primary-dark)',border:'1px solid var(--primary-200)'}}>{s.category}</span></td><td><span className={`badge bdg-${s.active?'certified':'rejected'}`}>{s.active?'Active':'Inactive'}</span></td><td><div className="tbl-actions"><button className="btn btn-ghost btn-sm" onClick={()=>{setForm({name:s.name,category:s.category,active:s.active});setModal(s);}}><Edit size={13}/>Edit</button><button className="btn btn-danger btn-sm" onClick={()=>del(s._id)}><Trash2 size={13}/>Delete</button></div></td></tr>))}{standards.length===0&&<tr><td colSpan={5} style={{textAlign:'center',padding:32,color:'var(--gray-400)'}}>No standards yet</td></tr>}</tbody></table></div>)}</div>
    {modal&&(<div className="modal-bg" onClick={()=>setModal(null)}><div className="modal-box" onClick={e=>e.stopPropagation()}><div className="modal-head"><div className="modal-title">{modal==='add'?'Add Standard':'Edit Standard'}</div><button className="modal-close" onClick={()=>setModal(null)}>✕</button></div><div className="modal-body"><div className="form-group"><label className="form-label">Standard Name *</label><input className="form-control" value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))} placeholder="e.g. ISO 9001:2015"/></div><div className="form-group"><label className="form-label">Category *</label><input className="form-control" value={form.category} onChange={e=>setForm(p=>({...p,category:e.target.value}))} placeholder="e.g. Quality Management"/></div><div className="form-group"><label className="form-label">Status</label><select className="form-control" value={form.active?'1':'0'} onChange={e=>setForm(p=>({...p,active:e.target.value==='1'}))}><option value="1">Active</option><option value="0">Inactive</option></select></div></div><div className="modal-foot"><button className="btn btn-ghost" onClick={()=>setModal(null)}>Cancel</button><button className="btn btn-primary" onClick={save} disabled={saving}>{saving?'Saving…':modal==='add'?<><Plus size={14}/>Create</>:<><Edit size={14}/>Save</>}</button></div></div></div>)}
  </Layout>);}
